[versions]
# --- Android / Kotlin toolchain
compileSdk = "36"
minSdk = "29"
jvmVersion = "21"

agp = "8.12.3"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.4"

# --- App versioning
appVersionName = "1.5"
appVersionCode = "16"

# --- AndroidX
androidxCore = "1.17.0"
appcompat = "1.7.1"
activityCompose = "1.12.2"
lifecycle = "2.10.0"
datastore = "1.2.0"
paging = "3.3.6"
room = "2.8.4"
securityCrypto = "1.1.0"
credentials = "1.5.0"

# --- Compose
# Для BOM не задавать вручную версии для compose libs
# foundation/material3/icons/etс должно подтягиваться BOM
composeBom = "2026.01.00"

# --- DI
hilt = "2.57.2"
androidxHilt = "1.3.0"

# --- Networking
retrofit = "3.0.0"
okhttp = "5.3.2"
gson = "2.13.2"

# --- Serialization / Coroutines
coroutines = "1.10.2"
kotlinxSerializationJson = "1.9.0"

# --- Media / Images / UI helpers
coil3 = "3.3.0"
media3 = "1.9.0"
accompanistSystemUiController = "0.36.0"
multiplatformMarkdownRendererM3 = "0.39.1"

# --- Navigation3
navigation3 = "1.0.0"
material3AdaptiveNav3 = "1.0.0-alpha03"

# --- Play Services
playServicesCast = "22.2.0"

# --- Tests
junit4 = "4.13.2"
androidxJunit = "1.3.0"
espresso = "3.7.0"
translate = "17.0.3"
languageId = "17.0.6"

[libraries]
# --- Base AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# --- Lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

# --- credentials
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }

# --- Compose (BOM)
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

androidx-foundation = { module = "androidx.compose.foundation:foundation" }
material3 = { module = "androidx.compose.material3:material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

# translate
translate = { module = "com.google.mlkit:translate", version.ref = "translate" }
language-id = { module = "com.google.mlkit:language-id", version.ref = "languageId" }

# --- Navigation3
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-navigation3-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
androidx-navigation3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive-navigation3", version.ref = "material3AdaptiveNav3" }

# --- Paging
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

# --- Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# --- DataStore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }

# --- Security
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

# --- Coroutines / Serialization
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# --- Network (Retrofit + OkHttp + Gson)
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# --- DI (Hilt)
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }

# --- Images / Media
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil3" }

androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

# --- UI helpers
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemUiController" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "multiplatformMarkdownRendererM3" }

# --- Play services
play-services-cast = { module = "com.google.android.gms:play-services-cast", version.ref = "playServicesCast" }

# --- Tests
junit = { module = "junit:junit", version.ref = "junit4" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


[bundles]
translate = [
    "translate",
    "language-id"
]

coroutines = [
    "kotlinx-coroutines-android",
]

lifecycle = [
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-ktx",
]

compose-core = [
    "androidx-core-ktx",
    "androidx-activity-compose",
    "androidx-foundation",
    "material3",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "androidx-material-icons-extended",
]

androidx-credentials = [
    "androidx-credentials",
    "androidx-credentials-play-services-auth"
]

compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest",
]

compose-test = [
    "androidx-ui-test-junit4",
]

navigation3 = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",
    "androidx-navigation3-viewmodel",
    "androidx-navigation3-adaptive",
]

hilt = [
    "dagger-hilt-android",
    "androidx-hilt-navigation-compose",
]

room = [
    "androidx-room-runtime",
    "androidx-room-ktx",
    "androidx-room-paging",
]

retrofit = [
    "retrofit",
    "converter-gson",
    "okhttp",
    "logging-interceptor",
    "urlconnection",
    "gson",
]

serialization-json = [
    "kotlinx-serialization-json",
]

coil = [
    "coil-compose",
    "coil-gif",
    "coil-video",
    "coil-network-okhttp",
]

paging = [
    "androidx-paging-runtime-ktx",
    "androidx-paging-compose",
]

media3 = [
    "androidx-media3-exoplayer",
    "androidx-media3-ui",
]

accompanist = [
    "accompanist-systemuicontroller",
]

datastore = [
    "androidx-datastore-preferences",
    "androidx-datastore-preferences-core",
]

test-core = [
    "junit",
    "androidx-junit",
    "androidx-espresso-core",
]